### ISSUE TITLE
Feature Request: Add notifications support

### ISSUE THREAD

**Issue by MrVibe** [imath/bp-custom-addon#2]
This is good new initiative, simplifying component adding into the BP core. Please include how we can add notifications related to the component you are creating.
We extended the Core component in our plugins like this.
`
    class BP_Course_Component extends BP_Component {
	public function setup_globals($args=array()) {
		global $bp;
		$globals = array(
			'slug'                  => BP_COURSE_SLUG,
			'root_slug'             => isset( $bp->pages->{$this->id}->slug ) ? $bp->pages->{$this->id}->slug : BP_COURSE_SLUG,
			'has_directory'         => true, // Set to false if not required
			'directory_title'       => _x( 'Course Directory', 'Course directory title', 'wplms' ),
			'notification_callback' => 'bp_course_format_notifications', // Function handling notifications when component is Course
			'search_string'         => __( 'Search courses ...', 'wplms' ),
			//'global_tables'         => $global_tables
		);
		parent::setup_globals( $globals );

	}`

**Comment by imath** [comment]
Hi @MrVibe 

Sure, I will add it 👍
